/**
 * Timetable Module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const TIMETABLE_PERMISSIONS = {
    CREATE: PERMISSIONS.TIMETABLE.CREATE,
    READ: PERMISSIONS.TIMETABLE.READ,
    UPDATE: PERMISSIONS.TIMETABLE.UPDATE,
    DELETE: PERMISSIONS.TIMETABLE.DELETE,
} as const;

export const TIMETABLE_ERROR_CODES = {
    NOT_FOUND: 'TIMETABLE_NOT_FOUND',
    ENTRY_NOT_FOUND: 'TIMETABLE_ENTRY_NOT_FOUND',
    TEACHER_CONFLICT: 'TEACHER_CONFLICT',
    SECTION_CONFLICT: 'SECTION_CONFLICT',
    SUBJECT_NOT_MAPPED: 'SUBJECT_NOT_MAPPED_TO_CLASS',
    SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
    TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
    TEACHER_WRONG_BRANCH: 'TEACHER_WRONG_BRANCH',
    CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
    SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
    PERIOD_NOT_FOUND: 'PERIOD_NOT_FOUND',
    ACADEMIC_YEAR_NOT_FOUND: 'ACADEMIC_YEAR_NOT_FOUND',
} as const;


export const DAYS_OF_WEEK = [
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday',
] as const;

export type DayOfWeek = (typeof DAYS_OF_WEEK)[number];
