/**
 * Staff Attendance Sub-module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const STAFF_ATTENDANCE_PERMISSIONS = {
    CREATE: PERMISSIONS.STAFF_ATTENDANCE.CREATE,
    READ: PERMISSIONS.STAFF_ATTENDANCE.READ,
    UPDATE: PERMISSIONS.STAFF_ATTENDANCE.UPDATE,
} as const;

export const STAFF_ATTENDANCE_STATUS = {
    PRESENT: 'present',
    ABSENT: 'absent',
    LATE: 'late',
    HALF_DAY: 'half_day',
    ON_LEAVE: 'on_leave',
} as const;

export type StaffAttendanceStatus = (typeof STAFF_ATTENDANCE_STATUS)[keyof typeof STAFF_ATTENDANCE_STATUS];

export const STAFF_ATTENDANCE_STATUS_OPTIONS = [
    STAFF_ATTENDANCE_STATUS.PRESENT,
    STAFF_ATTENDANCE_STATUS.ABSENT,
    STAFF_ATTENDANCE_STATUS.LATE,
    STAFF_ATTENDANCE_STATUS.HALF_DAY,
    STAFF_ATTENDANCE_STATUS.ON_LEAVE,
] as const;

export const STAFF_ATTENDANCE_ERROR_CODES = {
    NOT_FOUND: 'STAFF_ATTENDANCE_NOT_FOUND',
    DUPLICATE_RECORD: 'DUPLICATE_STAFF_ATTENDANCE',
    STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
    STAFF_INACTIVE: 'STAFF_INACTIVE',
    STAFF_WRONG_BRANCH: 'STAFF_WRONG_BRANCH',
    FUTURE_DATE_NOT_ALLOWED: 'FUTURE_DATE_NOT_ALLOWED',
} as const;
