/**
 * Marks Module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const MARKS_PERMISSIONS = {
    ENTER: PERMISSIONS.MARKS.ENTER,
    UPDATE: PERMISSIONS.MARKS.UPDATE,
    READ: PERMISSIONS.MARKS.READ,
} as const;

export const MARKS_ERROR_CODES = {
    NOT_FOUND: 'MARKS_NOT_FOUND',
    SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
    STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
    STUDENT_NOT_ENROLLED: 'STUDENT_NOT_ENROLLED',
    DUPLICATE_ENTRY: 'DUPLICATE_MARKS_ENTRY',
    MARKS_EXCEED_MAX: 'MARKS_EXCEED_MAX',
    EXAM_NOT_STARTED: 'EXAM_NOT_STARTED',
    EXAM_PUBLISHED: 'CANNOT_MODIFY_PUBLISHED_EXAM_MARKS',
    BEFORE_EXAM_DATE: 'CANNOT_ENTER_MARKS_BEFORE_EXAM',
} as const;
