import { PERMISSIONS } from '@school-erp/shared';

export const USER_PERMISSIONS = {
  CREATE: PERMISSIONS.USER.CREATE,
  READ_ALL: PERMISSIONS.USER.READ_ALL,
  READ_BRANCH: PERMISSIONS.USER.READ_BRANCH,
  READ_OWN: PERMISSIONS.USER.READ_OWN,
  UPDATE_ALL: PERMISSIONS.USER.UPDATE_ALL,
  UPDATE_BRANCH: PERMISSIONS.USER.UPDATE_BRANCH,
  UPDATE_OWN: PERMISSIONS.USER.UPDATE_OWN,
  DELETE: PERMISSIONS.USER.DELETE,
  ASSIGN_ROLE: PERMISSIONS.ROLE.ASSIGN,
} as const;

export const USER_ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  CANNOT_DELETE_SELF: 'CANNOT_DELETE_SELF',
  CANNOT_DELETE_LAST_ADMIN: 'CANNOT_DELETE_LAST_ADMIN',
  INVALID_USER_TYPE: 'INVALID_USER_TYPE',
  INVALID_BRANCH_ASSIGNMENT: 'INVALID_BRANCH_ASSIGNMENT',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_ASSIGNED: 'ROLE_ALREADY_ASSIGNED',
  CANNOT_REMOVE_LAST_ADMIN_ROLE: 'CANNOT_REMOVE_LAST_ADMIN_ROLE',
  BRANCH_NOT_ACCESSIBLE: 'BRANCH_NOT_ACCESSIBLE',
} as const;

export const USER_STATUS_OPTIONS = ['active', 'inactive', 'pending', 'suspended'] as const;

export const USER_TYPE_OPTIONS = ['admin', 'staff', 'teacher', 'parent', 'student'] as const;

export const DEFAULT_PASSWORD_LENGTH = 16;

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
