import { PERMISSIONS } from './permissions';

export interface RoleDefinition {
  code: string;
  name: string;
  description: string;
  isSystem: boolean;
  permissions: string[];
}

export const SYSTEM_ROLE_CODES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  BRANCH_ADMIN: 'BRANCH_ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  TEACHER: 'TEACHER',
  ACCOUNTANT: 'ACCOUNTANT',
  LIBRARIAN: 'LIBRARIAN',
  TRANSPORT_MANAGER: 'TRANSPORT_MANAGER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
} as const;

export type SystemRoleCode = (typeof SYSTEM_ROLE_CODES)[keyof typeof SYSTEM_ROLE_CODES];

export const SYSTEM_ROLES: Record<SystemRoleCode, RoleDefinition> = {
  [SYSTEM_ROLE_CODES.SUPER_ADMIN]: {
    code: SYSTEM_ROLE_CODES.SUPER_ADMIN,
    name: 'Super Administrator',
    description: 'Full system access, manages all tenants',
    isSystem: true,
    permissions: [
      PERMISSIONS.TENANT.CREATE,
      PERMISSIONS.TENANT.READ_ALL,
      PERMISSIONS.TENANT.UPDATE_ALL,
      PERMISSIONS.TENANT.DELETE,
      PERMISSIONS.AUDIT.READ_TENANT,
    ],
  },

  [SYSTEM_ROLE_CODES.TENANT_ADMIN]: {
    code: SYSTEM_ROLE_CODES.TENANT_ADMIN,
    name: 'Tenant Administrator',
    description: 'Full tenant access, manages branches and users',
    isSystem: true,
    permissions: [
      PERMISSIONS.TENANT.READ_OWN,
      PERMISSIONS.TENANT.UPDATE_OWN,
      PERMISSIONS.BRANCH.CREATE,
      PERMISSIONS.BRANCH.READ_ALL,
      PERMISSIONS.BRANCH.UPDATE_ALL,
      PERMISSIONS.BRANCH.DELETE,
      PERMISSIONS.USER.CREATE,
      PERMISSIONS.USER.READ_ALL,
      PERMISSIONS.USER.UPDATE_ALL,
      PERMISSIONS.USER.DELETE,
      PERMISSIONS.ROLE.CREATE,
      PERMISSIONS.ROLE.READ,
      PERMISSIONS.ROLE.UPDATE,
      PERMISSIONS.ROLE.DELETE,
      PERMISSIONS.ROLE.ASSIGN,
      PERMISSIONS.ACADEMIC_YEAR.CREATE,
      PERMISSIONS.ACADEMIC_YEAR.READ,
      PERMISSIONS.ACADEMIC_YEAR.UPDATE,
      PERMISSIONS.ACADEMIC_YEAR.DELETE,
      PERMISSIONS.ACADEMIC_YEAR.ACTIVATE,
      PERMISSIONS.SUBJECT.CREATE,
      PERMISSIONS.SUBJECT.READ,
      PERMISSIONS.SUBJECT.UPDATE,
      PERMISSIONS.SUBJECT.DELETE,
      PERMISSIONS.SETTINGS.TENANT_READ,
      PERMISSIONS.SETTINGS.TENANT_UPDATE,
      PERMISSIONS.REPORT.GENERATE_TENANT,
      PERMISSIONS.AUDIT.READ_TENANT,
      PERMISSIONS.ANNOUNCEMENT.CREATE_TENANT,
    ],
  },

  [SYSTEM_ROLE_CODES.BRANCH_ADMIN]: {
    code: SYSTEM_ROLE_CODES.BRANCH_ADMIN,
    name: 'Branch Administrator',
    description: 'Full branch access',
    isSystem: true,
    permissions: [
      PERMISSIONS.BRANCH.READ_OWN,
      PERMISSIONS.BRANCH.UPDATE_OWN,
      PERMISSIONS.USER.READ_BRANCH,
      PERMISSIONS.USER.UPDATE_BRANCH,
      PERMISSIONS.STUDENT.CREATE,
      PERMISSIONS.STUDENT.READ_BRANCH,
      PERMISSIONS.STUDENT.UPDATE,
      PERMISSIONS.STUDENT.DELETE,
      PERMISSIONS.STUDENT.ENROLL,
      PERMISSIONS.STUDENT.PROMOTE,
      PERMISSIONS.GUARDIAN.CREATE,
      PERMISSIONS.GUARDIAN.READ_BRANCH,
      PERMISSIONS.GUARDIAN.UPDATE,
      PERMISSIONS.GUARDIAN.DELETE,
      PERMISSIONS.STAFF.CREATE,
      PERMISSIONS.STAFF.READ_BRANCH,
      PERMISSIONS.STAFF.UPDATE,
      PERMISSIONS.STAFF.DELETE,
      PERMISSIONS.CLASS.CREATE,
      PERMISSIONS.CLASS.READ,
      PERMISSIONS.CLASS.UPDATE,
      PERMISSIONS.CLASS.DELETE,
      PERMISSIONS.SECTION.CREATE,
      PERMISSIONS.SECTION.READ,
      PERMISSIONS.SECTION.UPDATE,
      PERMISSIONS.SECTION.DELETE,
      PERMISSIONS.ATTENDANCE.MARK,
      PERMISSIONS.ATTENDANCE.READ_BRANCH,
      PERMISSIONS.ATTENDANCE.UPDATE,
      PERMISSIONS.ATTENDANCE.REPORT,
      PERMISSIONS.FEE.STRUCTURE_CREATE,
      PERMISSIONS.FEE.STRUCTURE_READ,
      PERMISSIONS.FEE.STRUCTURE_UPDATE,
      PERMISSIONS.FEE.ASSIGN,
      PERMISSIONS.FEE.COLLECT,
      PERMISSIONS.FEE.READ_BRANCH,
      PERMISSIONS.FEE.CONCESSION,
      PERMISSIONS.FEE.REPORT,
      PERMISSIONS.EXAM.CREATE,
      PERMISSIONS.EXAM.READ,
      PERMISSIONS.EXAM.UPDATE,
      PERMISSIONS.EXAM.DELETE,
      PERMISSIONS.EXAM.SCHEDULE,
      PERMISSIONS.EXAM.RESULT_ENTRY,
      PERMISSIONS.EXAM.RESULT_READ_BRANCH,
      PERMISSIONS.EXAM.PUBLISH,
      PERMISSIONS.EXAM.REPORT_CARD,
      PERMISSIONS.TIMETABLE.CREATE,
      PERMISSIONS.TIMETABLE.READ_BRANCH,
      PERMISSIONS.TIMETABLE.UPDATE,
      PERMISSIONS.TIMETABLE.DELETE,
      PERMISSIONS.ANNOUNCEMENT.CREATE_BRANCH,
      PERMISSIONS.ANNOUNCEMENT.READ,
      PERMISSIONS.ANNOUNCEMENT.UPDATE,
      PERMISSIONS.ANNOUNCEMENT.DELETE,
      PERMISSIONS.ANNOUNCEMENT.PUBLISH,
      PERMISSIONS.COMMUNICATION.READ,
      PERMISSIONS.TRANSPORT.MANAGE,
      PERMISSIONS.TRANSPORT.READ,
      PERMISSIONS.TRANSPORT.ASSIGN,
      PERMISSIONS.LIBRARY.MANAGE,
      PERMISSIONS.LIBRARY.READ,
      PERMISSIONS.LIBRARY.ISSUE,
      PERMISSIONS.LIBRARY.RETURN,
      PERMISSIONS.REPORT.GENERATE_BRANCH,
      PERMISSIONS.REPORT.SCHEDULE,
      PERMISSIONS.AUDIT.READ_BRANCH,
      PERMISSIONS.SETTINGS.BRANCH_READ,
      PERMISSIONS.SETTINGS.BRANCH_UPDATE,
    ],
  },

  [SYSTEM_ROLE_CODES.PRINCIPAL]: {
    code: SYSTEM_ROLE_CODES.PRINCIPAL,
    name: 'Principal',
    description: 'School principal with oversight access',
    isSystem: true,
    permissions: [
      PERMISSIONS.BRANCH.READ_OWN,
      PERMISSIONS.STUDENT.READ_BRANCH,
      PERMISSIONS.STAFF.READ_BRANCH,
      PERMISSIONS.CLASS.READ,
      PERMISSIONS.SECTION.READ,
      PERMISSIONS.ATTENDANCE.READ_BRANCH,
      PERMISSIONS.ATTENDANCE.REPORT,
      PERMISSIONS.FEE.READ_BRANCH,
      PERMISSIONS.FEE.REPORT,
      PERMISSIONS.EXAM.READ,
      PERMISSIONS.EXAM.PUBLISH,
      PERMISSIONS.EXAM.REPORT_CARD,
      PERMISSIONS.TIMETABLE.READ_BRANCH,
      PERMISSIONS.ANNOUNCEMENT.CREATE_BRANCH,
      PERMISSIONS.ANNOUNCEMENT.READ,
      PERMISSIONS.ANNOUNCEMENT.UPDATE,
      PERMISSIONS.ANNOUNCEMENT.DELETE,
      PERMISSIONS.ANNOUNCEMENT.PUBLISH,
      PERMISSIONS.REPORT.GENERATE_BRANCH,
      PERMISSIONS.AUDIT.READ_BRANCH,
    ],
  },

  [SYSTEM_ROLE_CODES.TEACHER]: {
    code: SYSTEM_ROLE_CODES.TEACHER,
    name: 'Teacher',
    description: 'Teaching staff with class management access',
    isSystem: true,
    permissions: [
      PERMISSIONS.STUDENT.READ_BRANCH,
      PERMISSIONS.CLASS.READ,
      PERMISSIONS.SECTION.READ,
      PERMISSIONS.ATTENDANCE.MARK,
      PERMISSIONS.ATTENDANCE.READ_BRANCH,
      PERMISSIONS.EXAM.READ,
      PERMISSIONS.EXAM.RESULT_ENTRY,
      PERMISSIONS.TIMETABLE.READ_OWN,
      PERMISSIONS.ANNOUNCEMENT.READ,
      PERMISSIONS.LIBRARY.READ,
      PERMISSIONS.LIBRARY.ISSUE,
    ],
  },

  [SYSTEM_ROLE_CODES.ACCOUNTANT]: {
    code: SYSTEM_ROLE_CODES.ACCOUNTANT,
    name: 'Accountant',
    description: 'Financial management access',
    isSystem: true,
    permissions: [
      PERMISSIONS.STUDENT.READ_BRANCH,
      PERMISSIONS.FEE.STRUCTURE_CREATE,
      PERMISSIONS.FEE.STRUCTURE_READ,
      PERMISSIONS.FEE.STRUCTURE_UPDATE,
      PERMISSIONS.FEE.ASSIGN,
      PERMISSIONS.FEE.COLLECT,
      PERMISSIONS.FEE.READ_BRANCH,
      PERMISSIONS.FEE.CONCESSION,
      PERMISSIONS.FEE.REPORT,
      PERMISSIONS.REPORT.GENERATE_BRANCH,
    ],
  },

  [SYSTEM_ROLE_CODES.LIBRARIAN]: {
    code: SYSTEM_ROLE_CODES.LIBRARIAN,
    name: 'Librarian',
    description: 'Library management access',
    isSystem: true,
    permissions: [
      PERMISSIONS.STUDENT.READ_BRANCH,
      PERMISSIONS.STAFF.READ_BRANCH,
      PERMISSIONS.LIBRARY.MANAGE,
      PERMISSIONS.LIBRARY.READ,
      PERMISSIONS.LIBRARY.ISSUE,
      PERMISSIONS.LIBRARY.RETURN,
    ],
  },

  [SYSTEM_ROLE_CODES.TRANSPORT_MANAGER]: {
    code: SYSTEM_ROLE_CODES.TRANSPORT_MANAGER,
    name: 'Transport Manager',
    description: 'Transport operations management',
    isSystem: true,
    permissions: [
      PERMISSIONS.STUDENT.READ_BRANCH,
      PERMISSIONS.TRANSPORT.MANAGE,
      PERMISSIONS.TRANSPORT.READ,
      PERMISSIONS.TRANSPORT.ASSIGN,
    ],
  },

  [SYSTEM_ROLE_CODES.PARENT]: {
    code: SYSTEM_ROLE_CODES.PARENT,
    name: 'Parent/Guardian',
    description: 'Parent portal access',
    isSystem: true,
    permissions: [
      PERMISSIONS.STUDENT.READ_OWN,
      PERMISSIONS.ATTENDANCE.READ_OWN,
      PERMISSIONS.FEE.READ_OWN,
      PERMISSIONS.EXAM.RESULT_READ_OWN,
      PERMISSIONS.TIMETABLE.READ_OWN,
      PERMISSIONS.ANNOUNCEMENT.READ,
    ],
  },

  [SYSTEM_ROLE_CODES.STUDENT]: {
    code: SYSTEM_ROLE_CODES.STUDENT,
    name: 'Student',
    description: 'Student portal access',
    isSystem: true,
    permissions: [
      PERMISSIONS.STUDENT.READ_OWN,
      PERMISSIONS.ATTENDANCE.READ_OWN,
      PERMISSIONS.EXAM.RESULT_READ_OWN,
      PERMISSIONS.TIMETABLE.READ_OWN,
      PERMISSIONS.ANNOUNCEMENT.READ,
      PERMISSIONS.LIBRARY.READ,
    ],
  },
};

export function getRoleByCode(code: string): RoleDefinition | undefined {
  return SYSTEM_ROLES[code as SystemRoleCode];
}

export function isSystemRole(code: string): boolean {
  return Object.values(SYSTEM_ROLE_CODES).includes(code as SystemRoleCode);
}

export function getRolePermissions(code: string): string[] {
  const role = getRoleByCode(code);
  return role?.permissions ?? [];
}
