import { PERMISSIONS } from '@school-erp/shared';

export const ROLE_PERMISSIONS = {
  CREATE: PERMISSIONS.ROLE.CREATE,
  READ: PERMISSIONS.ROLE.READ,
  UPDATE: PERMISSIONS.ROLE.UPDATE,
  DELETE: PERMISSIONS.ROLE.DELETE,
  ASSIGN: PERMISSIONS.ROLE.ASSIGN,
} as const;

export const ROLE_ERROR_CODES = {
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
  CANNOT_DELETE_SYSTEM_ROLE: 'CANNOT_DELETE_SYSTEM_ROLE',
  CANNOT_UPDATE_SYSTEM_ROLE: 'CANNOT_UPDATE_SYSTEM_ROLE',
  INVALID_PERMISSION: 'INVALID_PERMISSION',
  PRIVILEGE_ESCALATION: 'PRIVILEGE_ESCALATION',
  ROLE_IN_USE: 'ROLE_IN_USE',
} as const;

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
