/**
 * Exam Schedules Constants
 */
export const SCHEDULE_ERROR_CODES = {
    NOT_FOUND: 'SCHEDULE_NOT_FOUND',
    CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
    SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
    EXAM_NOT_FOUND: 'EXAM_NOT_FOUND',
    SUBJECT_NOT_MAPPED: 'SUBJECT_NOT_MAPPED_TO_CLASS',
    TIME_CONFLICT: 'SCHEDULE_TIME_CONFLICT',
    EXAM_PUBLISHED: 'CANNOT_MODIFY_PUBLISHED_EXAM_SCHEDULE',
} as const;
