/**
 * Academic Years Sub-module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const ACADEMIC_YEAR_PERMISSIONS = {
    CREATE: PERMISSIONS.ACADEMIC_YEAR.CREATE,
    READ: PERMISSIONS.ACADEMIC_YEAR.READ,
    UPDATE: PERMISSIONS.ACADEMIC_YEAR.UPDATE,
    DELETE: PERMISSIONS.ACADEMIC_YEAR.DELETE,
    ACTIVATE: PERMISSIONS.ACADEMIC_YEAR.ACTIVATE,
} as const;

export const ACADEMIC_YEAR_ERROR_CODES = {
    NOT_FOUND: 'ACADEMIC_YEAR_NOT_FOUND',
    ALREADY_EXISTS: 'ACADEMIC_YEAR_ALREADY_EXISTS',
    INVALID_DATES: 'INVALID_DATE_RANGE',
    CANNOT_DELETE_ACTIVE: 'CANNOT_DELETE_ACTIVE_YEAR',
    ALREADY_ACTIVE: 'ACADEMIC_YEAR_ALREADY_ACTIVE',
} as const;

export const ACADEMIC_YEAR_STATUS_OPTIONS = ['draft', 'active', 'completed'] as const;
export type AcademicYearStatus = (typeof ACADEMIC_YEAR_STATUS_OPTIONS)[number];

export const PAGINATION_DEFAULTS = {
    PAGE: 1,
    LIMIT: 20,
    MAX_LIMIT: 100,
} as const;
