/**
 * Attendance Module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const ATTENDANCE_PERMISSIONS = {
    CREATE: PERMISSIONS.ATTENDANCE.CREATE,
    READ: PERMISSIONS.ATTENDANCE.READ,
    UPDATE: PERMISSIONS.ATTENDANCE.UPDATE,
} as const;

export const ATTENDANCE_STATUS = {
    PRESENT: 'present',
    ABSENT: 'absent',
    LATE: 'late',
    HALF_DAY: 'half_day',
    EXCUSED: 'excused',
} as const;

export type AttendanceStatus = (typeof ATTENDANCE_STATUS)[keyof typeof ATTENDANCE_STATUS];

export const ATTENDANCE_STATUS_OPTIONS = [
    ATTENDANCE_STATUS.PRESENT,
    ATTENDANCE_STATUS.ABSENT,
    ATTENDANCE_STATUS.LATE,
    ATTENDANCE_STATUS.HALF_DAY,
    ATTENDANCE_STATUS.EXCUSED,
] as const;

export const ATTENDANCE_ERROR_CODES = {
    NOT_FOUND: 'ATTENDANCE_NOT_FOUND',
    DUPLICATE_RECORD: 'DUPLICATE_ATTENDANCE_RECORD',
    STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
    STUDENT_NOT_ENROLLED: 'STUDENT_NOT_ENROLLED',
    STUDENT_INACTIVE: 'STUDENT_INACTIVE',
    SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
    ACADEMIC_YEAR_NOT_FOUND: 'ACADEMIC_YEAR_NOT_FOUND',
    DATE_OUTSIDE_ACADEMIC_YEAR: 'DATE_OUTSIDE_ACADEMIC_YEAR',
    CORRECTION_NOT_ALLOWED: 'CORRECTION_NOT_ALLOWED',
} as const;
