export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRY: '15m',
  ACCESS_TOKEN_EXPIRY_MS: 15 * 60 * 1000,

  REFRESH_TOKEN_EXPIRY: '7d',
  REFRESH_TOKEN_EXPIRY_MS: 7 * 24 * 60 * 60 * 1000,

  PASSWORD_RESET_EXPIRY: '1h',
  PASSWORD_RESET_EXPIRY_MS: 60 * 60 * 1000,

  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MS: 15 * 60 * 1000,

  MAX_ACTIVE_SESSIONS: 10,

  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,

  TOKEN_VERSION_KEY: 'tokenVersion',
} as const;

export const COOKIE_NAMES = {
  ACCESS_TOKEN: 'access_token',
  REFRESH_TOKEN: 'refresh_token',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  PASSWORD_REQUIRED: 'AUTH_PASSWORD_REQUIRED',
  PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
} as const;

export const JWT_ALGORITHMS = {
  HS256: 'HS256',
  HS384: 'HS384',
  HS512: 'HS512',
} as const;

export type JwtAlgorithm = (typeof JWT_ALGORITHMS)[keyof typeof JWT_ALGORITHMS];
