export {
  isValidUUID,
  assertUUID,
  generatePrefixedId,
  extractUUIDFromPrefixedId,
  normalizeUUID,
  compareUUIDs,
} from './uuid';

export {
  type DateInput,
  toDate,
  isValidDate,
  formatISO,
  formatDate,
  formatDateTime,
  formatDateShort,
  startOfDay,
  endOfDay,
  addDays,
  addMonths,
  addYears,
  differenceInDays,
  differenceInYears,
  isExpired,
  isFuture,
  isPast,
  isToday,
  getAcademicYear,
  calculateAge,
} from './dates';

export {
  capitalize,
  capitalizeWords,
  slugify,
  truncate,
  camelToSnake,
  snakeToCamel,
  kebabToCamel,
  camelToKebab,
  isNullOrEmpty,
  isNotNullOrEmpty,
  normalizeWhitespace,
  removeSpecialChars,
  escapeHtml,
  maskEmail,
  maskPhone,
  formatName,
  generateInitials,
  pluralize,
  generateSlug,
} from './strings';
