/**
 * Sections Sub-module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const SECTION_PERMISSIONS = {
    CREATE: PERMISSIONS.SECTION.CREATE,
    READ: PERMISSIONS.SECTION.READ,
    UPDATE: PERMISSIONS.SECTION.UPDATE,
    DELETE: PERMISSIONS.SECTION.DELETE,
} as const;

export const SECTION_ERROR_CODES = {
    NOT_FOUND: 'SECTION_NOT_FOUND',
    ALREADY_EXISTS: 'SECTION_CODE_ALREADY_EXISTS',
    CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
    STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
    STAFF_INACTIVE: 'STAFF_INACTIVE',
    STAFF_TENANT_MISMATCH: 'STAFF_TENANT_MISMATCH',
    HAS_DEPENDENCIES: 'SECTION_HAS_DEPENDENCIES',
    ALREADY_DELETED: 'SECTION_ALREADY_DELETED',
} as const;

export const PAGINATION_DEFAULTS = {
    PAGE: 1,
    LIMIT: 20,
    MAX_LIMIT: 100,
} as const;
