/**
 * Classes Sub-module Constants
 */
import { PERMISSIONS } from '@school-erp/shared';

export const CLASS_PERMISSIONS = {
    CREATE: PERMISSIONS.CLASS.CREATE,
    READ: PERMISSIONS.CLASS.READ,
    UPDATE: PERMISSIONS.CLASS.UPDATE,
    DELETE: PERMISSIONS.CLASS.DELETE,
} as const;

export const CLASS_ERROR_CODES = {
    NOT_FOUND: 'CLASS_NOT_FOUND',
    ALREADY_EXISTS: 'CLASS_CODE_ALREADY_EXISTS',
    ACADEMIC_YEAR_NOT_FOUND: 'ACADEMIC_YEAR_NOT_FOUND',
    BRANCH_MISMATCH: 'BRANCH_MISMATCH',
    HAS_DEPENDENCIES: 'CLASS_HAS_DEPENDENCIES',
    ALREADY_DELETED: 'CLASS_ALREADY_DELETED',
} as const;

export const PAGINATION_DEFAULTS = {
    PAGE: 1,
    LIMIT: 20,
    MAX_LIMIT: 100,
} as const;
